[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 79
known_third_party = ["app_config", "azureml", "beautifultable", "configs", "converters", "create_aml_env", "dacite", "dataclasses", "flair", "flask", "handlers", "helpers", "logger", "predictors", "processors", "prodigy", "pydash", "register_dataset", "repository", "repository_manager", "requests", "services", "sikriml", "spacy", "srsly", "tests", "train", "trainers", "utils", "yaml"]

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
(
  /(
      \.git
    | \.venv
    | \.vscode
  )/
)
'''

[tool.mypy]
ignore_missing_imports = true